name: ThePetiteMuse
favicon: null
layout_spectrum: 0.601478464435786
typography_spectrum: 0.9409191175363958
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f9f9'
    - '#bfc0c2'
    - '#e2a36d'
    - '#ac9782'
    - '#c8e9e0'
  brandStrength: 0.5
  lightness: 0.9375
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
